[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

; Подключаем только чистые асинхронные библиотеки без дубликатов
lib_deps =
    esphome/ESPAsyncTCP-esphome @ ^2.0.0
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

; Жесткая привязка к твоей плате на 11 порту
upload_port = COM11
monitor_port = COM11
