[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM3
monitor_port = COM3



; Оптимизация разделов флэш-памяти под асинхронный сервер
board_build.partitions = min_spiffs.csv

; Ссылки с пробелами для защиты от обрезания чатом (удалите пробелы при вставке!)
lib_deps =
    me-no-dev/AsyncTCP @ ^1.1.1
    https://github.com/me-no-dev/ESPAsyncWebServer.git
